name: flutter_challenge_hs
description: 'A Headspace Flutter Challenge'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.2.1
  get_it: ^7.6.9
  go_router: ^13.2.4
  sqflite: ^2.3.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.9
  bloc_test: ^9.1.7
  mocktail: ^1.0.3
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
